name: Build and Prettier
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - develop
      - main
  workflow_dispatch:
jobs:
  check-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Install packages
        run: npm ci
      - name: Run prettier
        run: npx prettier -c .
      - name: Build Otterscan
        run: npm run build
