on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Gnosis Integration Server
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Install packages
        run: npm ci
      - name: Build Otterscan
        run: npm run build
        env:
          VITE_CONFIG_JSON: ${{ secrets.CLOUDFLARE_INTEG_GNOSIS_SETTINGS }}
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=${{ secrets.CLOUDFLARE_INTEG_GNOSIS_PROJECT }} --commit-dirty=true